apiVersion: v1
kind: Deployment
metadata:
  name: sharded-memcache-ambassador

spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: shared-twemproxy
    spec:
  # This is the ambassador container
  - name: twemproxy
    image: ganomede/twemproxy
    command: ["nutcracker"]
    args: ["-c", "/etc/config/nutcracker.yaml", "-v", "7", "-s", "6222"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: shared-twem-config
