apiVersion: v1
kind: Pod
metadata:
  name: adapter-example
  namespace: default
spec:
  containers:
    - image: redis
    name: redis
    # Provide an adapter that implements the Prometheus interface
    - image: oliver006/redis_exporter
    name: adapter